### ISSUE TITLE
RxSwift dependency

### ISSUE THREAD

**Issue by troupmar** [Qase/QuantiLogger#7]
The current version of QuantiLogger depends on RxSwift library because the newly implemented WebLogger uses the reactive functionality. Such dependency is not included within Carthage nor CocoaPods. It means that RxSwift will not be automatically added (if not present within the target app just yet) when integrating QuantiLogger using Carthage or CocoaPods. A user will need to explicitly name RxSwift as another dependency.

It is necessary to edit the Carthage/CocoaPods configuration files so RxSwift is automatically included when integrating QuantiLogger as dependancy framework to the target app.

**Comment by jakubprusa** [comment]
We can take inspiration from this project RxBluetoothKit. Specifically this file: https://github.com/Polidea/RxBluetoothKit/blob/633d2e8844586c99cd03a48fe20bb9edd996f466/Package.swift

And more documentation about this file can be found here: https://swift.org/package-manager/

**Comment by troupmar** [comment]
CocoPods and Carthage dependencies are tested and all should work as expected.

New issue for Swift Package Manager support created: #8
